language: python
env:
  global:
  - secure: GGZUvnopK5qr0QTvELhdHSFRwelajF9/WB+UFYoBEgUhP9QcxJYxj9cPQj/vTZDTAapoKkjEIzAidoEWl88TY8ehVvNCuk94X2gqlUP0NaH7GtU8NBEv1jid8hOqgSz9Mn7d1lYVgCeW27tGPvsuZfHA3rXukAgolLF40XoLc9U=
  - secure: KShdt4xv2L+7Wp4DethcTIa/J3xABvha3LFBj5jF2Y+c2J/cIoZ+9TA7ycXuMpre9qhfCh5Hyhhj8YVNX+iyVBWkFe5EX6rluiE9ZOcPAXZcTrbw8eSGG+ToJZWut7lUZ4Z4JXZr4ldl1jLvunfvYEgJU4pcyUkwfMe2Rtf4toE=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage cpp-coveralls
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.ip.draw import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ip.draw ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
