language: python
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - secure: GGZUvnopK5qr0QTvELhdHSFRwelajF9/WB+UFYoBEgUhP9QcxJYxj9cPQj/vTZDTAapoKkjEIzAidoEWl88TY8ehVvNCuk94X2gqlUP0NaH7GtU8NBEv1jid8hOqgSz9Mn7d1lYVgCeW27tGPvsuZfHA3rXukAgolLF40XoLc9U=
    - secure: KShdt4xv2L+7Wp4DethcTIa/J3xABvha3LFBj5jF2Y+c2J/cIoZ+9TA7ycXuMpre9qhfCh5Hyhhj8YVNX+iyVBWkFe5EX6rluiE9ZOcPAXZcTrbw8eSGG+ToJZWut7lUZ4Z4JXZr4ldl1jLvunfvYEgJU4pcyUkwfMe2Rtf4toE=
  - python: 3.2
    env:
    - NUMPYSPEC===1.7.1
  - python: 3.3
    env:
    - NUMPYSPEC===1.8.0
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev
- if [ -n "${NUMPYSPEC}" ]; then sudo apt-get install -qq libatlas-dev libatlas-base-dev
  liblapack-dev gfortran; fi
- if [ -n "${NUMPYSPEC}" ]; then pip install --upgrade pip setuptools; fi
- if [ -n "${NUMPYSPEC}" ]; then pip install --find-links http://wheels.astropy.org/
  --find-links http://wheels2.astropy.org/ --use-wheel numpy$NUMPYSPEC sphinx nose;
  fi
- pip install cpp-coveralls
install:
- python bootstrap.py
- CFLAGS=-coverage ./bin/buildout
script:
- ./bin/python -c 'from bob.ip.draw import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ip.draw ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls --build-root=`pwd` --exclude=src
- ./src/bob.extension/scripts/upload-sphinx.sh
